### ISSUE TITLE
Log file sent has no content in builds

### ISSUE THREAD

**Issue by zyq0825** [ASecondGuy/BugReporter#5]
Sorry, I'm back again... As with my previous issue, my messages can now be sent through, but the log file actually shows no content:

![Screenshot 2024-08-19 151342](https://github.com/user-attachments/assets/38451c35-fbc0-4024-b652-c15f72d7141a)

However, it works fine in the editor or the debug builds:

![Screenshot 2024-08-19 151517](https://github.com/user-attachments/assets/7ab81e7c-956d-4c36-9d92-657c120260a3)

I'm using your newest codes for Godot 3. Sorry, I could have noticed it back then.

**Comment by zyq0825** [comment]
I tried printing out the payload in send_massage(), and I got this in the normal build log file:

--b808208910
Content-Disposition: form-data; name="payload_json"
Content-Type: application/json

{"attachments":[{"id":0}],"embeds":[{"color":15258703,"fields":[{"inline":false,"name":"Message:","value":"```\nbuild test\n```"}],"title":"Bug reported by playerid: 2078827880"}],"tts":false,"username":"From Soil to Bottle:"}
--b808208910
Content-Type: plain/text"
Content-Disposition: attachment; filename="godot.log"; name="files[0]";

--b808208910--

While in the editor it was: 

--b3240068670
Content-Disposition: form-data; name="payload_json"
Content-Type: application/json

{"attachments":[{"id":0}],"embeds":[{"color":15258703,"fields":[{"inline":false,"name":"Message:","value":"```\ntest\n```"}],"title":"Bug reported by playerid: 2078827880"}],"tts":false,"username":"From Soil to Bottle:"}
--b3240068670
Content-Type: plain/text"
Content-Disposition: attachment; filename="godot.log"; name="files[0]";

Godot Engine v3.5.3.stable.custom_build.406243c82 - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce GTX 1070/PCIe/SSE2
Async. shader compilation: OFF
 
--b3240068670--

It's really strange...

**Comment by ASecondGuy** [comment]
That should only happen if the log file is empty.

`application/run/flush_stdout_on_print = true` should fix it.
That way the logs will be written to the file when something is printed.
That is generally not recommended for release builds because of the slight performance impact it can have, but it is required for this.
I think by default it is only written when the game is closed or the buffer is full but I might be wrong.

Thanks for pointing this out. It is something the README should mention.

**Comment by zyq0825** [comment]
Thanks! That's it.
